import { useState } from 'react'
import { displayCell, formatTimestamp, instrumentFromDataRow, instrumentText, isDataRow, safeText, sourceText, type DataRow } from './businessData'
import { calibratedProbability, humanize, opportunityState, providerStatus, rankedOpportunities } from './presentation'
import { Details, EmptyState, Facts, Sparkline, Status } from './BusinessPrimitives'

export type OpenInstrument = (instrument: string, row: DataRow) => void
function InstrumentLink({ row, onOpen }: { row: DataRow; onOpen?: OpenInstrument }) {
  const instrument = instrumentFromDataRow(row)
  const name = instrumentText(row.instrument ?? row.symbol ?? row.asset ?? row.name)
  return instrument && onOpen ? <button className="text-button instrument-link" onClick={() => onOpen(instrument, row)}>{name} <span aria-hidden="true">↗</span></button> : <strong>{name}</strong>
}
export function MarketScreener({ rows, onOpen, compact = false, searching = false }: { rows: DataRow[]; onOpen?: OpenInstrument; compact?: boolean; searching?: boolean }) {
  const [sort, setSort] = useState('default')
  const sorted = [...rows].sort((a, b) => sort === 'asset' ? instrumentText(a.instrument ?? a.symbol).localeCompare(instrumentText(b.instrument ?? b.symbol)) : sort === 'change' ? (typeof b.change_percent === 'number' ? b.change_percent : -Infinity) - (typeof a.change_percent === 'number' ? a.change_percent : -Infinity) : 0)
  if (!rows.length) return <EmptyState title={searching ? "No markets match your search." : "No markets reported yet."} detail="Market observations will appear when available."/>
  return <><div className="list-toolbar"><span>{rows.length} monitored markets</span><label>Sort <select value={sort} onChange={e => setSort(e.target.value)}><option value="default">Backend order</option><option value="asset">Asset</option><option value="change">Change</option></select></label></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Asset</th><th>Price</th><th>Change</th>{!compact && <><th>Trend</th><th>Signal</th></>}<th>Data status</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{sorted.map((row, i) => <tr key={i}><td><InstrumentLink row={row} onOpen={onOpen}/><Sparkline data={row}/></td><td>{displayCell('price', row.price, row)}</td><td className={typeof row.change_percent === 'number' ? row.change_percent < 0 ? 'negative' : 'positive' : ''}>{displayCell('change_percent', row.change_percent, row)}</td>{!compact && <><td>{humanize(row.trend ?? row.regime)}</td><td>{humanize(row.signal ?? row.action)}</td></>}<td><Status value={isDataRow(row.quality) ? row.quality.freshness_status ?? row.quality.status : row.status ?? row.quality}/></td><td><Details data={row} title="Details"/></td></tr>)}</tbody></table></div></>
}
export function OpportunityBoard({ rows, onOpen, limit, searching = false }: { rows: DataRow[]; onOpen?: OpenInstrument; limit?: number; searching?: boolean }) {
  const [filter, setFilter] = useState('focus')
  const visible = rankedOpportunities(rows).filter(row => filter === 'all' || (filter === 'focus' ? !['rejected', 'disqualified'].includes(opportunityState(row)) : opportunityState(row) === filter))
  return <>{!limit && <div className="filter-tabs" aria-label="Opportunity filter">{[['focus', 'Qualified & watching'], ['qualified', 'Qualified'], ['rejected', 'Rejected'], ['all', 'All']].map(([key, title]) => <button key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{title}</button>)}</div>}{!visible.length ? <EmptyState title={searching ? 'No opportunities match your search and filter.' : filter === 'rejected' ? 'No rejected opportunities reported.' : 'No opportunity currently meets NOVA’s entry requirements.'} detail="NOVA waits for sufficient evidence before qualifying an entry."/> : <div className="opportunity-board">{visible.slice(0, limit ?? visible.length).map((row, i) => <article className="opportunity-row" key={i}><div className="opportunity-heading"><span className="rank">{safeText(row.rank, '—')}</span><InstrumentLink row={row} onOpen={onOpen}/><Status value={row.qualification_status ?? row.status ?? row.decision}/></div><div className="opportunity-signal"><strong>{humanize(row.direction)}</strong><span>{safeText(row.horizon)}</span><span>{calibratedProbability(row)}</span></div><Facts row={row} fields={[[ 'expected_net_return', 'Expected edge · after costs' ], ['estimated_costs', 'Costs'], ['quality', 'Quality'], ['action', 'NOVA decision']]}/><p className="readable-summary">{humanize(row.summary ?? row.reason ?? row.reasons, 'Analysis is available in the details below.')}</p><details className="analysis-details"><summary>View complete analysis</summary><p>Invalidation: {humanize(row.invalidation ?? row.invalidation_conditions)}</p><Details data={row}/></details></article>)}</div>}</>
}
export function PositionList({ rows, onOpen, closed = false }: { rows?: DataRow[]; onOpen?: OpenInstrument; closed?: boolean }) {
  if (!rows) return <EmptyState title={closed ? 'Closed trades not reported.' : 'Position state not reported.'} detail="This response does not include the position list."/>
  if (!rows.length) return <EmptyState title={closed ? 'No closed PAPER trades yet.' : 'No open PAPER positions.'} detail={closed ? 'Completed trades will appear here.' : 'Capital remains available for a qualified opportunity.'}/>
  return <div className="position-list">{rows.map((row, i) => <article key={i}><div className="position-heading"><InstrumentLink row={row} onOpen={onOpen}/><Status value={row.direction ?? row.side}/><strong className={typeof (row.unrealized_pnl ?? row.realized_pnl) === 'number' ? Number(row.unrealized_pnl ?? row.realized_pnl) < 0 ? 'negative' : 'positive' : ''}>{safeText(row.unrealized_pnl ?? row.realized_pnl)} <small>P&L</small></strong></div><Facts row={row} fields={[[ 'entry_price', 'Entry' ], [closed ? 'exit_price' : 'current_price', closed ? 'Exit' : 'Current'], ['duration', 'Duration'], ['action', 'NOVA decision']]}/><Sparkline data={row}/><Details data={row} title="Position analysis & execution details"/></article>)}</div>
}
export function IntelligenceFeed({ rows, onOpen, searching = false }: { rows: DataRow[]; onOpen?: OpenInstrument; searching?: boolean }) {
  if (!rows.length) return <EmptyState title={searching ? "No events match your search." : "No events reported yet."} detail="New intelligence will appear here as it is detected."/>
  const sorted = [...rows].sort((a, b) => (Date.parse(String(b.published_at ?? b.timestamp)) || 0) - (Date.parse(String(a.published_at ?? a.timestamp)) || 0))
  return <div className="intelligence-feed">{sorted.map((row, i) => <article key={i}><div className="feed-time"><time>{formatTimestamp(row.published_at ?? row.timestamp ?? row.observed_at)}</time><span>{row.source ? sourceText(row.source) : Array.isArray(row.source_ids) ? `${row.source_ids.length} sources` : "Source not reported"}</span></div><div><h3>{humanize(row.title ?? row.summary ?? row.event_type, 'Market event')}</h3>{row.title !== undefined && <p>{safeText(row.summary, '')}</p>}<div className="feed-meta"><span>{safeText(row.entities ?? row.instruments ?? row.affected_assets, 'Assets not reported')}</span><span>Impact: {humanize(row.impact ?? row.importance)}</span><span>Evidence: {humanize(row.evidence_quality ?? row.quality)}</span></div><p>{humanize(row.why_it_matters ?? row.analysis, '')}</p>{instrumentFromDataRow(row) && <InstrumentLink row={row} onOpen={onOpen}/>}<Details data={row} title="View NOVA analysis & provenance"/></div></article>)}</div>
}
export function ActivityTimeline({ rows }: { rows: DataRow[] }) {
  if (!rows.length) return <EmptyState title="No PAPER activity reported yet."/>
  return <ol className="activity-timeline">{rows.map((row, i) => <li key={i}><time>{formatTimestamp(row.timestamp ?? row.created_at)}</time><div><strong>{humanize(row.action ?? row.to_status)}</strong><p>{humanize(row.reason ?? row.reasons ?? row.summary)}</p><Facts row={row} fields={[[ 'instrument', 'Instrument' ], ['fees', 'Costs'], ['realized_pnl', 'Realized P&L']]}/><Details data={row} title="Execution details"/></div></li>)}</ol>
}
export function SystemHealth({ data }: { data: DataRow }) {
  const providers: DataRow[] = Array.isArray(data.provider_health) ? data.provider_health.filter(isDataRow) : isDataRow(data.provider_health) ? Object.entries(data.provider_health).map(([name, value]) => isDataRow(value) ? { name, ...value } : { name, status: value }) : []
  const errors = isDataRow(data.provider_errors) ? Object.entries(data.provider_errors) : []
  return <div className="system-groups"><div className="subsystem-row"><strong>Overall health</strong><Status value={data.status}/></div>{['market_data', 'trader', 'scheduler', 'forecasting', 'calibration', 'research', 'storage', 'retention', 'watchdog', 'outcomes'].map(key => <details className="subsystem" key={key}><summary><span>{humanize(key)}</span><Status value={isDataRow(data[key]) ? data[key].status : typeof data[key] === 'string' ? data[key] : undefined}/></summary><Details data={data[key] ?? 'Not checked'} title="Diagnostics"/></details>)}<h3>Data providers</h3>{!providers.length && !errors.length && <EmptyState title="Provider health not checked."/>}{providers.map((row, i) => <div className="provider-row" key={i}><span>{safeText(row.provider ?? row.name)}</span><span className="status-text">{providerStatus(row.status)}</span><Details data={row}/></div>)}{errors.map(([provider, error]) => <div className="provider-row" key={provider}><strong>{provider}</strong><span className="status-text warning-text">Degraded</span><Details data={error}/></div>)}<Details data={data} title="All system diagnostics"/></div>
}




