import { useCallback, useEffect, useMemo, useState } from 'react'
import { getInstrumentData, getTradeDetail, type InstrumentDataSet, type MarketTimeframe } from '../../api/novaApi'
import { ErrorState, Skeleton } from '../business/BusinessPage'
import { InstrumentChart } from './InstrumentChart'
import { Details } from '../business/BusinessPrimitives'
import { calibratedProbability } from '../business/presentation'
import { isRow, mapCandles, mapRows, mapTradeMarkers, tradeSummary, type JsonRow, type TradeMarker } from './marketData'

const layerNames=['Trades','Events','Patterns','Forecasts','Volume'] as const
type Layer=typeof layerNames[number]
const initialLayers=()=>{try{return {...Object.fromEntries(layerNames.map(v=>[v,true])),...JSON.parse(localStorage.getItem('nova-chart-layers')??'{}')} as Record<Layer,boolean>}catch{return Object.fromEntries(layerNames.map(v=>[v,true])) as Record<Layer,boolean>}}
const text=(value:unknown,fallback:unknown='—')=>value===null||value===undefined||value===''?String(fallback):String(value)
const number=(value:unknown)=>typeof value==='number'?new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(value):'—'
const date=(value:unknown)=>typeof value==='string'?new Date(value).toLocaleString():'—'
const quality=(value:unknown)=>isRow(value)?text(value.quality_score??value.label):text(value)

export function InstrumentPage({instrument,context,onBack}:{instrument:string;context:JsonRow;onBack:()=>void}){
 const [timeframe,setTimeframe]=useState<MarketTimeframe>('1h');const [data,setData]=useState<InstrumentDataSet>();const [error,setError]=useState('');const [layers,setLayers]=useState(initialLayers);const [selected,setSelected]=useState<TradeMarker>();const [detail,setDetail]=useState<JsonRow>()
 useEffect(()=>{const controller=new AbortController();getInstrumentData(instrument,timeframe,controller.signal).then(next=>{setData(next);setError('')}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unavailable')});return()=>controller.abort()},[instrument,timeframe])
 useEffect(()=>{localStorage.setItem('nova-chart-layers',JSON.stringify(layers))},[layers])
 useEffect(()=>{if(!selected?.positionId)return;const controller=new AbortController();getTradeDetail(selected.positionId,controller.signal).then(setDetail).catch(()=>setDetail(undefined));return()=>controller.abort()},[selected])
 const candles=useMemo(()=>data?mapCandles(data.history):[],[data]);const markers=useMemo(()=>data?mapTradeMarkers(data.markers):[],[data])
 const forecasts=useMemo(()=>data?mapRows(data.forecasts,'forecasts'):[],[data]);const events=useMemo(()=>data?mapRows(data.events,'events'):[],[data]);const patterns=useMemo(()=>data?mapRows(data.patterns,'patterns'):[],[data])
 const quote=useMemo(()=>data?mapRows(data.market,'quotes')[0]:undefined,[data]);const available=(data?.history.available_timeframes as MarketTimeframe[]|undefined)??[];const latest=candles.at(-1);const latestMarker=markers.at(-1);const selectTrade=useCallback((marker:TradeMarker)=>setSelected(marker),[])
 const toggle=(layer:Layer)=>setLayers(current=>({...current,[layer]:!current[layer]}));const summary=detail?tradeSummary(detail):undefined
 return <section className="instrument-page"><header className="instrument-header"><button onClick={onBack} className="back-button">← Back</button><div><p className="eyebrow">INSTRUMENT INTELLIGENCE</p><h1>{instrument}</h1><p>{text(quote?.instrument&&isRow(quote.instrument)?quote.instrument.kind:null,'Market instrument')} · {text(quote?.source&&isRow(quote.source)?quote.source.provider:null,'Provider unavailable')}</p></div><div className="instrument-price"><strong>{number(quote?.price??latest?.close)}</strong><span className={typeof quote?.change_percent === "number" ? quote.change_percent < 0 ? "negative" : "positive" : undefined}>{typeof quote?.change_percent === "number" ? `${number(quote.change_percent)}%` : "Change unavailable"}</span><small>{text(data?.history.freshness&&isRow(data.history.freshness)?data.history.freshness.latest_at:null,'Freshness unavailable')}</small></div><span className="paper-badge">AUTO_PAPER · SIMULATED</span></header>
 <div className="instrument-kpis"><div><span>NOVA ACTION</span><strong>{latestMarker?.action??text(context.action)}</strong></div><div><span>STAR SCORE</span><strong>{number(context.star_score)}</strong></div><div><span>REGIME</span><strong>{text(context.regime??(forecasts[0]?.feature_snapshot&&isRow(forecasts[0].feature_snapshot)?forecasts[0].feature_snapshot.regime:null))}</strong></div><div><span>EXPECTED NET RETURN</span><strong>{number(context.expected_net_return??forecasts[0]?.expected_return)}</strong></div><div><span>CALIBRATED PROBABILITY</span><strong>{forecasts[0]?calibratedProbability(forecasts[0]):'—'}</strong></div></div>
 {Boolean(context.opportunity_id||context.event_id||context.position_id)&&<Details data={context} title="Selected analysis · context & provenance"/>}
 <section className="chart-panel"><div className="chart-toolbar"><div className="timeframes">{(['1m','5m','1h','1d'] as MarketTimeframe[]).map(item=><button key={item} disabled={data!==undefined&&!available.includes(item)} className={timeframe===item?'active':''} onClick={()=>setTimeframe(item)}>{item}</button>)}</div><div className="layer-controls">{layerNames.map(layer=><label key={layer}><input type="checkbox" checked={layers[layer]} onChange={()=>toggle(layer)}/>{layer}</label>)}</div></div>{error?<ErrorState message={error}/>:!data?<Skeleton/>:candles.length<2?<div className="empty-history"><strong>Insufficient market history</strong><span>{text(data.history.freshness&&isRow(data.history.freshness)?data.history.freshness.provider:null,'Provider unavailable')} · {text(data.history.freshness&&isRow(data.history.freshness)?data.history.freshness.latest_at:null,'Freshness unavailable')}</span></div>:<InstrumentChart candles={candles} markers={markers} events={events} patterns={patterns} forecasts={forecasts} focusTimestamp={typeof (context.detected_at??context.published_at??context.timestamp)==='string'?String(context.detected_at??context.published_at??context.timestamp):undefined} showTrades={layers.Trades} showEvents={layers.Events} showPatterns={layers.Patterns} showForecasts={layers.Forecasts} showVolume={layers.Volume} onSelectTrade={selectTrade}/>}</section>
 <div className="instrument-grid"><section className="business-panel intelligence-panel"><div className="panel-heading"><div><small>MULTI-TIMEFRAME</small><h2>Signal matrix</h2></div></div><table className="signal-matrix"><thead><tr><th>TF</th><th>Trend</th><th>Pattern</th><th>Forecast</th><th>Quality</th></tr></thead><tbody>{(['5m','15m','1h','4h','1d'] as const).map(tf=>{const p=patterns.find(v=>v.timeframe===tf);const f=forecasts.find(v=>v.horizon===tf||isRow(v.feature_snapshot)&&isRow(v.feature_snapshot.multi_timeframe_context));const context=f&&isRow(f.feature_snapshot)&&isRow(f.feature_snapshot.multi_timeframe_context)&&isRow(f.feature_snapshot.multi_timeframe_context.timeframes)?f.feature_snapshot.multi_timeframe_context.timeframes:{};return <tr key={tf}><td>{tf}</td><td>{text(context[tf])}</td><td>{text(p?.pattern_type)}</td><td>{text(f?.direction)}</td><td>{quality(p?.quality??f?.calibration_quality)}</td></tr>})}</tbody></table></section>
 {layers.Forecasts&&<section className="business-panel intelligence-panel"><div className="panel-heading"><div><small>HONEST FORECASTS</small><h2>Forecast outlook</h2></div></div><div className="overlay-list">{forecasts.slice(0,5).map((item,index)=><article key={text(item.forecast_id,index)}><div><strong>{text(item.direction)} · {text(item.horizon)}</strong><span>{date(item.created_at)} → {date(item.due_at)}</span></div><b>{calibratedProbability(item)}</b><small>Expected return {number(item.expected_return)} · {text(item.direction)}</small><Details data={item} title="Calibration & provenance"/></article>)}{!forecasts.length&&<p>— No persisted forecast</p>}</div></section>}
 {layers.Events&&<section className="business-panel intelligence-panel"><div className="panel-heading"><div><small>EVENT TIMELINE</small><h2>Events</h2></div></div><div className="overlay-list">{events.slice(0,8).map((item,index)=><article key={text(item.event_id,index)}><div><strong>{text(item.event_type)}</strong><span>{date(item.published_at)}</span></div><p>{text(item.summary)}</p><small>Importance {number(item.source_quality_score)} · sources {Array.isArray(item.source_ids)?item.source_ids.join(', '):'—'}</small></article>)}{!events.length&&<p>— No persisted event</p>}</div></section>}
 {layers.Patterns&&<section className="business-panel intelligence-panel"><div className="panel-heading"><div><small>DETECTED ONLY</small><h2>Patterns</h2></div></div><div className="overlay-list">{patterns.slice(0,8).map((item,index)=><article key={`${text(item.pattern_type)}-${index}`}><div><strong>{text(item.pattern_type)}</strong><span>{text(item.timeframe)} · {date(item.detected_at)}</span></div><small>Strength {number(item.strength)} · quality {quality(item.quality)} · invalidation {Array.isArray(item.invalidation_conditions)?item.invalidation_conditions.join(', '):'—'}</small></article>)}{!patterns.length&&<p>— No persisted pattern</p>}</div></section>}</div>
 {selected&&<aside className="trade-drawer"><div className="drawer-head"><div><small>PAPER TRADE INSPECTOR</small><h2>{selected.action} · {instrument}</h2></div><button onClick={()=>setSelected(undefined)}>×</button></div><div className="trade-facts"><span>Execution<strong>{number(selected.executionPrice)}</strong></span><span>Quantity<strong>{number(selected.quantity)}</strong></span><span>Fees<strong>{number(selected.fees)}</strong></span><span>Slippage<strong>{number(selected.slippage)}</strong></span></div>{detail?<><div className="trade-timeline">{mapRows(detail,'timeline').map((item,index)=><div key={index}><i/><span>{date(item.timestamp)}</span><strong>{text(item.to_status)}</strong><small>{Array.isArray(item.reasons)?item.reasons.join(' · '):'—'}</small></div>)}</div><div className="cost-waterfall"><span>Gross result<b>{number(summary?.gross)}</b></span><span>− Fees<b>{number(summary?.fees)}</b></span><span>− Spread / slippage<b>{number(summary?.slippage)}</b></span><span className="net">= Net result<b>{number(summary?.net)}</b></span><span>MFE / MAE<b>{number(summary?.mfe)} / {number(summary?.mae)}</b></span><span>Capture ratio<b>{number(summary?.capture)}</b></span></div></>:<p className="drawer-loading">Detailed lifecycle unavailable; marker fields remain verified.</p>}<section className="why-panel"><h3>WHY NOVA ACTED</h3><p>{Array.isArray(selected.reason)?selected.reason.join(' · '):text(selected.reason)}</p><small>No generated explanation — persisted reasons only.</small></section></aside>}
 </section>
}

